name: Call FastAPI Endpoint Every 8 Hours

on:
  schedule:
    - cron: '0 */8 * * *' # Runs every 8 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  call-fastapi:
    runs-on: ubuntu-latest
    steps:
      - name: Call FastAPI Endpoint
        run: |
          curl -X GET "https://goluxai-fastapi-production.up.railway.app/insertNextDay" \
                -H 'accept: application/json'
